[project]
name = "fastpeek"
version = "0.1.0"
description = "An utility for quickly peeking at git repositories"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
fastpeek = "main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
